### ISSUE TITLE
Slack Invite Request

### ISSUE THREAD

**Issue by madibalive** [zubairq/pilot#28]
Hi, really love your project, am looking to make this, the one  project i get into am currently mapping out the project/code  architecture/outline, if there is any diagram you to represent logic/architecture would love any guidance  mapping every part of the codebase, lastly need access to the slack group.

my current email is madibafeed@outlook.com

Thanks You.

**Comment by zubairq** [comment]
Invited. Are you sure you want to join, you will be the first to join Slack as I am the only team member who is public facing. Working on an architecture document at the moment, which I will be happy to share

**Comment by madibalive** [comment]
Sure, would be glad to join, I have seen people do crude so many times, it kinda weird that it  not automated at least for enterprise users, who just require it work, no need for fancy ui and stuff, saw retool and other no code platform, this is probably some version of how the future would play out. 
Thanks for the invite.

**Comment by zubairq** [comment]
Yes, you are right. Amazing how there is no Automated CRUD system for Enterprise, although there are tools like Retool that you can get hosted on site

**Comment by h5gs** [comment]
can you please invite me to slack maurya.ravindra84 at gmail com - Thanks for awesome tool and I am willing to contribute, I am developer and have similar plans
